# numpy & scipy functions for MLE

In [1]:
import numpy as np
from scipy import optimize
from scipy.stats import norm
from scipy.stats import multivariate_normal

In [2]:
class FakeData(object):
    def __init__(self, N, p, beta, sigma_squared, rng=None):
        if not rng: 
            rng = np.random.RandomState()
        X = rng.uniform(size=N * p).reshape((N, p))
        error = rng.normal(loc=0, scale=sigma_squared ** 0.5, size=N).reshape((N, 1))
        X_times_beta = X @ beta
        assert X_times_beta.shape == (N, 1), X_times_beta.shape
        y = X_times_beta + error
        assert y.shape == (N, 1), y.shape
        self.X = X
        self.y = y
        return


In [3]:
N = 10
beta = np.array([3.0, -5.0, 1.0])
p = len(beta)
beta = beta.reshape((p, 1))
sigma_squared = 5.0
theta_truth = tuple(float(b) for b in beta) + (sigma_squared,)

In [4]:
# make y, X
rng = np.random.RandomState(seed=0)
fake_data = FakeData(N, p, beta, sigma_squared, rng=rng)
y, X = fake_data.y, fake_data.X
y.shape, X.shape

((10, 1), (10, 3))

In [5]:
norm.pdf(
    x=y[:, 0],
    loc=(X @ beta)[:, 0],
    scale=sigma_squared ** 0.5
)

array([0.12278966, 0.13546229, 0.01357466, 0.06196118, 0.17822573,
       0.17531404, 0.05511334, 0.0606179 , 0.17628349, 0.16610072])

In [6]:
norm.pdf(
    x=y[:, 0],
    loc=(X @ beta)[:, 0],
    scale=sigma_squared ** 0.5
)

array([0.12278966, 0.13546229, 0.01357466, 0.06196118, 0.17822573,
       0.17531404, 0.05511334, 0.0606179 , 0.17628349, 0.16610072])

In [7]:
np.prod(norm.pdf(
    x=y[:, 0],
    loc=(X @ beta)[:, 0],
    scale=sigma_squared ** 0.5
))

4.2761866448473535e-11

In [8]:
multivariate_normal.pdf(
    x=y[:, 0],
    mean=(X @ beta)[:, 0],
    cov=sigma_squared
)

4.2761866448473644e-11

In [9]:
np.log(norm.pdf(
    x=y[:, 0],
    loc=(X @ beta)[:, 0],
    scale=sigma_squared ** 0.5
))

array([-2.09728246, -1.99906195, -4.29955052, -2.78124725, -1.72470441,
       -1.74117639, -2.89836355, -2.80316509, -1.73566184, -1.79516094])

In [10]:
norm.logpdf(
    x=y[:, 0],
    loc=(X @ beta)[:, 0],
    scale=sigma_squared ** 0.5
)

array([-2.09728246, -1.99906195, -4.29955052, -2.78124725, -1.72470441,
       -1.74117639, -2.89836355, -2.80316509, -1.73566184, -1.79516094])

In [11]:
-1 * norm.logpdf(
    x=y[:, 0],
    loc=(X @ beta)[:, 0],
    scale=sigma_squared ** 0.5
)

array([2.09728246, 1.99906195, 4.29955052, 2.78124725, 1.72470441,
       1.74117639, 2.89836355, 2.80316509, 1.73566184, 1.79516094])

In [12]:
# log likelihood of the truth!
-1 * sum(norm.logpdf(
    x=y[:, 0],
    loc=(X @ beta)[:, 0],
    scale=sigma_squared ** 0.5
))

23.875374381321276